app = 'weather-mx'
primary_region = 'lax'

[env]
  DATABASE_URL = "sqlite:////data/weather.db"
  HOST = "0.0.0.0"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1

[[mounts]]
  source = "weather_data"
  destination = "/data"
